### ISSUE TITLE
Version mismatch for 1.20.1

### ISSUE THREAD

**Issue by Therkelsen** [LatvianModder/HDFont#1]
Currently, the 1.20.1 version complains about a version mismatch in game. Any idea why?

https://github.com/Therkelsen/echoes_of_the_wilderness/issues/5

**Comment by LatvianModder** [comment]
It complains because minecraft didn't have version ranges up until 1.20.2. It should still work fine

**Comment by Therkelsen** [comment]
Thank you!

**Comment by smmmadden** [comment]
The reason there is a version mismatch is because the pack_format should be set to 15 (1.20.x).  If the pack_mcmeta is updated from 8 to 15, the warning goes away.  This is a very common issue with forgetting to increment the pack version each release.
